# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeStrengths' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LifeStrengths
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
                                                          'Core',
                                                          'RCTActionSheet',
                                                          'RCTAnimation',
                                                          'RCTGeolocation',
                                                          'RCTImage',
                                                          'RCTLinkingIOS',
                                                          'RCTNetwork',
                                                          'RCTSettings',
                                                          'RCTText',
                                                          'RCTVibration',
                                                          'RCTWebSocket',
                                                          'BatchedBridge'
                                                          ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  target 'LifeStrengthsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end
