# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeStrengths' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LifeStrengths
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'LifeStrengths-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  end

  target 'LifeStrengthsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
